spring.application.name=codecomp
server.port=8081

# ---------------- DATABASE ----------------
spring.datasource.url=jdbc:postgresql://postgres:5432/codecomp
spring.datasource.username=postgres
spring.datasource.password=postgres

# ---------------- JPA ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---------------- REDIS ----------------
spring.data.redis.host=redis
spring.data.redis.port=6379

# ---------------- RABBITMQ ----------------
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2

# ---------------- RATE LIMIT ----------------
rate.limit.max=5
rate.limit.window=10000

# ---------------- OAUTH2 ----------------
spring.security.oauth2.client.registration.google.client-id=907452387067-tkfvv287ohefo703umcnhlhrojp74atn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code