spring.application.name=codecomp

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/coding_platform
spring.datasource.username=postgres
spring.datasource.password=password

! HIBERNATE/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

! REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

! Rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2

! Rate-Limits
rate.limit.max=5
rate.limit.window=10000