spring.application.name=codecomp

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/coding_platform
spring.datasource.username=postgres
spring.datasource.password=password

! HIBERNATE/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

! REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

! Rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2

! Rate-Limits
rate.limit.max=5
rate.limit.window=10000

! Oauth2
spring.security.oauth2.client.registration.google.client-id=907452387067-tkfvv287ohefo703umcnhlhrojp74atn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code